; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const LANDMARK_SPECIAL           ; 00

DEF KANTO_LANDMARK EQU const_value
	const LANDMARK_PALLET_TOWN
	const LANDMARK_ROUTE_1
	const LANDMARK_VIRIDIAN_CITY
	const LANDMARK_ROUTE_2
	const LANDMARK_PEWTER_CITY
	const LANDMARK_ROUTE_3
	const LANDMARK_MT_MOON
	const LANDMARK_ROUTE_4
	const LANDMARK_CERULEAN_CITY
	const LANDMARK_ROUTE_24
	const LANDMARK_ROUTE_25
	const LANDMARK_ROUTE_5
	const LANDMARK_UNDERGROUND_PATH
	const LANDMARK_ROUTE_6
	const LANDMARK_VERMILION_CITY
	const LANDMARK_DIGLETTS_CAVE
	const LANDMARK_ROUTE_7
	const LANDMARK_ROUTE_8
	const LANDMARK_ROUTE_9
	const LANDMARK_ROCK_TUNNEL
	const LANDMARK_ROUTE_10
	const LANDMARK_POWER_PLANT
	const LANDMARK_LAVENDER_TOWN
	const LANDMARK_LAV_RADIO_TOWER
	const LANDMARK_CELADON_CITY
	const LANDMARK_SAFFRON_CITY
	const LANDMARK_ROUTE_11
	const LANDMARK_ROUTE_12
	const LANDMARK_ROUTE_13
	const LANDMARK_ROUTE_14
	const LANDMARK_ROUTE_15
	const LANDMARK_ROUTE_16
	const LANDMARK_ROUTE_17
	const LANDMARK_ROUTE_18
	const LANDMARK_FUCHSIA_CITY
	const LANDMARK_ROUTE_19
	const LANDMARK_ROUTE_20
	const LANDMARK_SEAFOAM_ISLANDS
	const LANDMARK_CINNABAR_ISLAND
	const LANDMARK_ROUTE_21
	const LANDMARK_ROUTE_22
	const LANDMARK_VICTORY_ROAD
	const LANDMARK_ROUTE_23
	const LANDMARK_INDIGO_PLATEAU
	const LANDMARK_ROUTE_26
	const LANDMARK_ROUTE_27
	const LANDMARK_TOHJO_FALLS
	const LANDMARK_ROUTE_28
DEF KANTO_LANDMARK_LAST EQU const_value - 1

DEF JOHTO_LANDMARK EQU const_value
	const LANDMARK_NEW_BARK_TOWN
	const LANDMARK_ROUTE_29
	const LANDMARK_CHERRYGROVE_CITY
	const LANDMARK_ROUTE_30
	const LANDMARK_ROUTE_31
	const LANDMARK_VIOLET_CITY
	const LANDMARK_SPROUT_TOWER
	const LANDMARK_ROUTE_32
	const LANDMARK_RUINS_OF_ALPH
	const LANDMARK_UNION_CAVE
	const LANDMARK_ROUTE_33
	const LANDMARK_AZALEA_TOWN
	const LANDMARK_SLOWPOKE_WELL
	const LANDMARK_ILEX_FOREST
	const LANDMARK_ROUTE_34
	const LANDMARK_GOLDENROD_CITY
	const LANDMARK_RADIO_TOWER
	const LANDMARK_ROUTE_35
	const LANDMARK_NATIONAL_PARK
	const LANDMARK_ROUTE_36
	const LANDMARK_ROUTE_37
	const LANDMARK_ECRUTEAK_CITY
	const LANDMARK_TIN_TOWER
	const LANDMARK_BURNED_TOWER
	const LANDMARK_ROUTE_38
	const LANDMARK_ROUTE_39
	const LANDMARK_OLIVINE_CITY
	const LANDMARK_LIGHTHOUSE
	const LANDMARK_BATTLE_TOWER
	const LANDMARK_ROUTE_40
	const LANDMARK_WHIRL_ISLANDS
	const LANDMARK_ROUTE_41
	const LANDMARK_CIANWOOD_CITY
	const LANDMARK_ROUTE_42
	const LANDMARK_MT_MORTAR
	const LANDMARK_MAHOGANY_TOWN
	const LANDMARK_ROUTE_43
	const LANDMARK_LAKE_OF_RAGE
	const LANDMARK_ROUTE_44
	const LANDMARK_ICE_PATH
	const LANDMARK_BLACKTHORN_CITY
	const LANDMARK_DRAGONS_DEN
	const LANDMARK_ROUTE_45
	const LANDMARK_DARK_CAVE
	const LANDMARK_ROUTE_46
	const LANDMARK_SILVER_CAVE
DEF JOHTO_LANDMARK_LAST EQU const_value - 1

DEF OTHER_LANDMARK EQU const_value
	const LANDMARK_FAST_SHIP         ; 5f

DEF NUM_LANDMARKS EQU const_value

; used in CaughtData
	const_def $7f, -1
	const LANDMARK_EVENT             ; $7f
	const LANDMARK_GIFT              ; $7e

; Regions
	const_def
	const JOHTO_REGION ; 0
	const KANTO_REGION ; 1
DEF NUM_REGIONS EQU const_value
